In [11]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [13]:
import pandas as pd

url = "https://github.com/nflverse/nflverse-data/releases/download/pbp/play_by_play_2025.csv"

cols = [
    "play_type",
    "down",
    "ydstogo",
    "yardline_100",
    "qtr",
    "score_differential",
    "game_seconds_remaining"
]

df = pd.read_csv(url, usecols=cols)

# keep only run/pass
df = df[df["play_type"].isin(["run", "pass"])]

# sample for speed
df = df.sample(10000, random_state=42)

print(df.head())

       yardline_100  game_seconds_remaining  qtr  down  ydstogo play_type  \
32644          58.0                  3493.0    1   1.0       10       run
11852          51.0                   652.0    4   3.0        2       run
16091          22.0                  1817.0    2   1.0       10      pass
34905          25.0                  2142.0    2   2.0        4       run
40244          48.0                   619.0    4   1.0       10       run

       score_differential
32644                 0.0
11852                 0.0
16091                -7.0
34905                 4.0
40244               -11.0

In [17]:
print(df.shape)
print(df.info())
print(df.isnull().sum())

(10000, 7)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 32644 to 9635
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   yardline_100            10000 non-null  float64
 1   game_seconds_remaining  10000 non-null  float64
 2   qtr                     10000 non-null  int64
 3   down                    9957 non-null   float64
 4   ydstogo                 10000 non-null  int64
 5   play_type               10000 non-null  object
 6   score_differential      10000 non-null  float64
dtypes: float64(4), int64(2), object(1)
memory usage: 625.0+ KB
None
yardline_100               0
game_seconds_remaining     0
qtr                        0
down                      43
ydstogo                    0
play_type                  0
score_differential         0
dtype: int64

In [18]:
print(df["play_type"].value_counts(normalize=True))

pass    0.5723
run     0.4277
Name: play_type, dtype: float64

In [20]:
print(df["down"].value_counts())

1.0    4350
2.0    3293
3.0    2047
4.0     267
Name: down, dtype: int64

In [21]:
df["ydstogo"].describe()

count    10000.000000
mean         8.364700
std          3.909683
min          0.000000
25%          6.000000
50%         10.000000
75%         10.000000
max         36.000000
Name: ydstogo, dtype: float64

In [24]:
df['yardline_100'].describe()

count    10000.000000
mean        48.796700
std         23.844761
min          1.000000
25%         31.000000
50%         52.000000
75%         67.000000
max         99.000000
Name: yardline_100, dtype: float64

In [25]:
pd.crosstab(df["down"], df["play_type"], normalize="index")

play_type      pass       run
down
1.0        0.474943  0.525057
2.0        0.584270  0.415730
3.0        0.742062  0.257938
4.0        0.685393  0.314607

In [26]:
pd.crosstab(df["ydstogo"], df["play_type"], normalize="index")

play_type      pass       run
ydstogo
0          0.720930  0.279070
1          0.237925  0.762075
2          0.506394  0.493606
3          0.540943  0.459057
4          0.564257  0.435743
5          0.589212  0.410788
6          0.664016  0.335984
7          0.692308  0.307692
8          0.688889  0.311111
9          0.756032  0.243968
10         0.524276  0.475724
11         0.821656  0.178344
12         0.787402  0.212598
13         0.807692  0.192308
14         0.809524  0.190476
15         0.786885  0.213115
16         0.803922  0.196078
17         0.803922  0.196078
18         0.732143  0.267857
19         0.818182  0.181818
20         0.797872  0.202128
21         0.842105  0.157895
22         1.000000  0.000000
23         0.692308  0.307692
24         0.333333  0.666667
25         0.333333  0.666667
26         0.750000  0.250000
27         0.666667  0.333333
28         0.666667  0.333333
29         0.500000  0.500000
30         0.000000  1.000000
33         1.000000  0.000000
36         0.000000  1.000000

In [2]:
nfl_data = pd.read_csv('/Users/nati/Desktop/nfl-play-prediction-ai/data/nfl_plays.csv')

In [3]:
nfl_data

,posteam,yardline_100,game_seconds_remaining,qtr,down,ydstogo,play_type,score_differential
0,NaN,NaN,3600.0,1,NaN,0,NaN,NaN
1,ARI,35.0,3600.0,1,NaN,0,kickoff,0.0
2,ARI,78.0,3596.0,1,1.0,10,run,0.0
3,ARI,75.0,3558.0,1,2.0,7,pass,0.0
4,ARI,64.0,3520.0,1,1.0,10,pass,0.0
...,...,...,...,...,...,...,...,...
48766,NE,67.0,47.0,4,1.0,5,no_play,-16.0
48767,NE,62.0,39.0,4,1.0,10,pass,-16.0
48768,NE,53.0,20.0,4,2.0,1,pass,-16.0
48769,NE,53.0,12.0,4,3.0,1,pass,-16.0
48770,NE,NaN,0.0,4,NaN,0,NaN,-16.0

In [6]:
nfl_data['posteam'].nunique()

32

In [7]:
pip install nfl-data-py

Requirement already satisfied: nfl-data-py in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (0.3.3)
Requirement already satisfied: numpy<2.0,>=1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from nfl-data-py) (1.26.4)
Requirement already satisfied: pandas<2.0,>=1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from nfl-data-py) (1.5.3)
Requirement already satisfied: appdirs>1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from nfl-data-py) (1.4.4)
Requirement already satisfied: fastparquet>0.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from nfl-data-py) (2024.11.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas<2.0,>=1.0->nfl-data-py) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas<2.0,>=1.0->nfl-data-py) (2025.2)
Requirement already satisfied: cramjam>=2.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from fastparquet>0.5->nfl-data-py) (2.9.1)
Requirement already satisfied: fsspec in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from fastparquet>0.5->nfl-data-py) (2025.2.0)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from fastparquet>0.5->nfl-data-py) (24.0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-dateutil>=2.8.1->pandas<2.0,>=1.0->nfl-data-py) (1.16.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.